/*
 * PS2 Memory Card Trader
 *
 * Proportional bitmap font atlas - GENERATED by
 * scripts/gen_font_atlas.py, do NOT hand-edit.
 *
 * Glyphs are stored already squeezed to 0.75 horizontally (the
 * widescreen pre-compensation gs_render applies), so one texel
 * is exactly one physical framebuffer pixel and the atlas can be
 * blitted 1:1 with GS_FILTER_NEAREST. Every metric below is in
 * physical pixels; callers working in the 640x448 logical space
 * divide by that same 0.75.
 */
#ifndef FONT_DATA_H
#define FONT_DATA_H

#define FONT_ATLAS_WIDTH 512
#define FONT_ATLAS_HEIGHT 128
#define FONT_FIRST_CHAR 32
#define FONT_LAST_CHAR 126
#define FONT_GLYPH_COUNT 95

/* Font sizes, indices into font_glyphs / font_line_h. */
#define FONT_SMALL 0
#define FONT_MID 1
#define FONT_BIG 2
#define FONT_COUNT 3

typedef struct {
    short u, v;        /* texel origin in the atlas */
    short w, h;        /* size in texels = physical pixels */
    short xoff, yoff;  /* offset from the pen (x) and from the
                          top of the line box (y) */
    short adv;         /* pen advance */
} font_glyph;

extern unsigned char font_atlas_data[];
extern const font_glyph font_glyphs[FONT_COUNT][FONT_GLYPH_COUNT];
extern const short font_line_h[FONT_COUNT];

#endif
