/*
 * PS2 Memory Card Trader
 *
 * Button/dpad sprite pixel data - GENERATED by
 * scripts/gen_sprites_data.py from the PNGs in src/imgs, do NOT
 * hand-edit.
 *
 * Sprites are stored pre-squeezed to 0.75 horizontally, so one
 * texel is one physical framebuffer pixel when drawn at
 * logical_w logical pixels wide.
 */
#ifndef SPRITES_DATA_H
#define SPRITES_DATA_H

typedef enum {
    BTN_CROSS,
    BTN_CIRCLE,
    BTN_SQUARE,
    BTN_TRIANGLE,
    BTN_DPAD,
    BTN_TOP,
    BTN_BOTTOM,
    BTN_LEFT,
    BTN_RIGHT,
    BTN_L1,
    BTN_L2,
    BTN_R1,
    BTN_R2,
    BTN_SELECT,
    BTN_START,
    BTN_COUNT
} sprite_id;

/* Logical width every sprite is authored at; drawing one this
   wide makes the blit 1:1. */
#define SPRITE_NATIVE_SIZE 32

typedef struct {
    unsigned char *data;    /* RGBA32, alpha in the GS 0..0x80 range */
    short w, h;             /* texel size (physical pixels) */
    short logical_w, logical_h;  /* size in logical pixels */
} sprite_desc;

extern const sprite_desc sprite_table[BTN_COUNT];

#endif
